# Generated by Django 4.0.6 on 2022-10-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code_origin', models.CharField(max_length=2)),
                ('language_code_destiny', models.CharField(choices=[('en', 'English'), ('fr', 'Francais'), ('de', 'Deutch'), ('zh-Hans', 'Chinesse')], max_length=7)),
                ('text_to_translate', models.CharField(max_length=255)),
                ('text_translated', models.CharField(max_length=255)),
            ],
        ),
    ]
