# Generated by Django 4.0.6 on 2023-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_analyze', models.CharField(max_length=255)),
            ],
        ),
    ]
